### ISSUE TITLE
Add .nvmrc to project

### ISSUE THREAD

**Issue by szabomarius** [szabomarius/mojilogger#11]

**Comment by Kenny4297** [comment]
Hi @szabomarius , I'd like to help with this issue. Could you specify which Node.js version you'd like to be set in the .nvmrc file?

**Comment by szabomarius** [comment]
👋 , I think the latest stable node version should be the one 20.9.0. We can also update the ci/cd node version while we're at it

**Comment by Kenny4297** [comment]
Great I'm on it!

**Comment by szabomarius** [comment]
🥂 cheers appreciate the help!
